export const IPC = {
  PROJECTS: {
    GET_ALL: 'projects:getAll',
    GET_BY_ID: 'projects:getById',
    CREATE: 'projects:create',
    UPDATE: 'projects:update',
    DELETE: 'projects:delete',
  },
  BACKLINKS: {
    GET_BY_PROJECT: 'backlinks:getByProject',
    CREATE: 'backlinks:create',
    BULK_CREATE: 'backlinks:bulkCreate',
    COUNT: 'backlinks:count',
    GET_REFERRING_DOMAINS: 'backlinks:getReferringDomains',
  },
  OPPORTUNITIES: {
    GET_BY_PROJECT: 'opportunities:getByProject',
    CREATE: 'opportunities:create',
    UPDATE: 'opportunities:update',
    COUNT_BY_STATUS: 'opportunities:countByStatus',
  },
  COMPETITORS: {
    GET_BY_PROJECT: 'competitors:getByProject',
    CREATE: 'competitors:create',
    UPDATE: 'competitors:update',
    DELETE: 'competitors:delete',
  },
  DOMAINS: {
    GET_BY_PROJECT: 'domains:getByProject',
    CREATE: 'domains:create',
    UPDATE: 'domains:update',
  },
  PAGES: {
    GET_BY_PROJECT: 'pages:getByProject',
    CREATE: 'pages:create',
  },
  AGENT_TASKS: {
    GET_BY_PROJECT: 'agentTasks:getByProject',
    CREATE: 'agentTasks:create',
    UPDATE_STATUS: 'agentTasks:updateStatus',
    GET_PENDING: 'agentTasks:getPending',
  },
  APPROVALS: {
    GET_BY_PROJECT: 'approvals:getByProject',
    CREATE: 'approvals:create',
    UPDATE: 'approvals:update',
  },
  MONITORING: {
    GET_BY_PROJECT: 'monitoring:getByProject',
    GET_RECENT: 'monitoring:getRecent',
  },
  SETTINGS: {
    GET: 'settings:get',
    SET: 'settings:set',
    GET_ALL: 'settings:getAll',
  },
  BROWSER: {
    CONNECT: 'browser:connect',
    DISCONNECT: 'browser:disconnect',
    GET_STATUS: 'browser:getStatus',
    OPEN_URL: 'browser:openUrl',
    GET_PAGE_CONTENT: 'browser:getPageContent',
  },
  AGENTS: {
    START: 'agents:start',
    STOP: 'agents:stop',
    PAUSE: 'agents:pause',
    RESUME: 'agents:resume',
    GET_STATUS: 'agents:getStatus',
  },
  CRAWLER: {
    CRAWL_SITE: 'crawler:crawlSite',
    GET_PROGRESS: 'crawler:getProgress',
    STOP: 'crawler:stop',
  },
  PROVIDERS: {
    GET_ALL: 'providers:getAll',
    CONFIGURE: 'providers:configure',
    TEST: 'providers:test',
    GET_STATUS: 'providers:getStatus',
    TEST_GROQ: 'providers:testGroq',
    TEST_OPENROUTER: 'providers:testOpenRouter',
  },
  IMPORT: {
    CSV: 'import:csv',
    PREVIEW: 'import:preview',
  },
  EXPORT: {
    CSV: 'export:csv',
    JSON: 'export:json',
  },
  APP: {
    GET_VERSION: 'app:getVersion',
    GET_PLATFORM: 'app:getPlatform',
    GET_THEME: 'app:getTheme',
    SET_THEME: 'app:setTheme',
    MINIMIZE: 'app:minimize',
    MAXIMIZE: 'app:maximize',
    CLOSE: 'app:close',
    IS_MAXIMIZED: 'app:isMaximized',
  },
  SUBMISSIONS: {
    GET_PROFILE: 'submissions:getProfile',
    SAVE_PROFILE: 'submissions:saveProfile',
    GET_TARGETS: 'submissions:getTargets',
    DISCOVER_TARGETS: 'submissions:discoverTargets',
    QUALIFY_TARGETS: 'submissions:qualifyTargets',
    PREPARE_SUBMISSION: 'submissions:prepareSubmission',
    EXECUTE_SUBMISSION: 'submissions:executeSubmission',
    RESUME_AFTER_HUMAN: 'submissions:resumeAfterHuman',
    VERIFY_TARGET: 'submissions:verifyTarget',
    VERIFY_ALL: 'submissions:verifyAll',
    GET_STATS: 'submissions:getStats',
    GET_CAMPAIGNS: 'submissions:getCampaigns',
    CREATE_CAMPAIGN: 'submissions:createCampaign',
    UPDATE_CAMPAIGN: 'submissions:updateCampaign',
    GET_ATTEMPTS: 'submissions:getAttempts',
    BULK_QUEUE: 'submissions:bulkQueue',
  },
  ASSETS: {
    GET_ALL: 'assets:getAll',
    CREATE: 'assets:create',
    ANALYZE_PDF: 'assets:analyzePdf',
    GENERATE_BRIEF: 'assets:generateBrief',
    DELETE: 'assets:delete',
  },
} as const;
